name: Find Next Semver
description: Determine latest semantic version tag and compute the next one based on PR context.

inputs:
  bump-type:
    description: 'Optional: Directly specify the bump type (major, minor, patch, meta). If provided, skips branch type detection.'
    required: false
    default: ''
  major-branch-patterns:
    description: 'Comma-separated list of branch patterns for major version bumps (e.g., "major/,breaking/")'
    required: false
    default: 'major/'
  patch-branch-patterns:
    description: 'Comma-separated list of branch patterns for hotfix/patch version bumps (e.g., "hotfix/,patch/")'
    required: false
    default: 'hotfix/'
  meta-branch-patterns:
    description: 'Comma-separated list of branch patterns for non-version-bumping branches (e.g., "meta/,docs/")'
    required: false
    default: 'meta/'
  pat_token:
    description: 'GitHub Personal Access Token, required if bump-type is auto'
    required: false
    default: ''

outputs:
  latest:
    description: Latest tag found in the repository (vX.Y.Z)
    value: ${{ steps.run.outputs.latest }}
  new_tag:
    description: Next tag to create (vX.Y.Z)
    value: ${{ steps.run.outputs.new_tag }}
  version:
    description: Version without leading v (X.Y.Z)
    value: ${{ steps.run.outputs.version }}

runs:
  using: composite
  steps:
    - name: Detect branch type
      id: branch-type
      if: ${{ inputs.bump-type == '' || inputs.bump-type == 'auto' }}
      uses: j-moralejo-pinas/ci-cd-python/actions/detect-branch-type@main
      with:
        head-branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
        major-branch-patterns: ${{ inputs.major-branch-patterns }}
        patch-branch-patterns: ${{ inputs.patch-branch-patterns }}
        meta-branch-patterns: ${{ inputs.meta-branch-patterns }}

    - name: Find latest and compute next semver
      id: run
      shell: bash
      env:
        BUMP_TYPE_INPUT: ${{ inputs.bump-type }}
        DETECTED_BRANCH_TYPE: ${{ steps.branch-type.outputs.branch-type }}
        PAT_TOKEN: ${{ inputs.pat_token }}
      run: |
        bash "${GITHUB_ACTION_PATH}/find-next-semver.sh"
