name: Find Main PRs Between Releases
description: Find PR numbers on the main branch between the previous release tag and current commit, excluding patch branches.

inputs:
  token:
    description: GitHub token for gh CLI
    required: true
  repo:
    description: owner/repo slug
    required: true
  main_branch:
    description: Name of the main branch
    required: false
    default: main
  patch-branch-patterns:
    description: 'Comma-separated list of branch patterns to exclude (e.g., "hotfix/,patch/")'
    required: false
    default: 'hotfix/'

outputs:
  numbers:
    description: Space-separated PR numbers between releases
    value: ${{ steps.run.outputs.numbers }}
  prev_tag:
    description: Previous release tag (if any)
    value: ${{ steps.prev_release.outputs.prev_tag }}
  prev_commit:
    description: Previous release commit SHA
    value: ${{ steps.prev_release.outputs.prev_commit }}

runs:
  using: composite
  steps:
    - name: Find previous release commit
      id: prev_release
      uses: j-moralejo-pinas/ci-cd-python/actions/find-previous-release-commit@main
      with:
        main_branch: ${{ inputs.main_branch }}

    - name: Find PRs on main between releases
      id: run
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        REPO_SLUG: ${{ inputs.repo }}
        MAIN_BRANCH: ${{ inputs.main_branch }}
        PATCH_PATTERNS: ${{ inputs.patch-branch-patterns }}
        PREV_COMMIT: ${{ steps.prev_release.outputs.prev_commit }}
      run: |
        bash "${GITHUB_ACTION_PATH}/find-main-prs-between-releases.sh"
