name: Update Changelog
description: Slice changelog between releases and update CHANGELOG.rst

inputs:
  workflow_type:
    description: 'Type of workflow (gitflow or github-flow)'
    required: false
    default: 'gitflow'
  gh_token:
    description: 'GitHub token for gh CLI'
    required: true
  pat_token:
    description: 'GitHub PAT token for API access'
    required: true
  changelog_path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.rst'
  major-branch-patterns:
    description: 'Comma-separated list of branch patterns for major version bumps (e.g., "major/,breaking/")'
    required: false
    default: 'major/'
  hotfix-branch-patterns:
    description: 'Comma-separated list of branch patterns for hotfix/patch version bumps (e.g., "hotfix/,patch/")'
    required: false
    default: 'fix/,hotfix/,bugfix/'
  meta-branch-patterns:
    description: 'Comma-separated list of branch patterns for non-version-bumping branches (e.g., "meta/,docs/")'
    required: false
    default: 'meta/'

outputs:
  did_push:
    description: 'Whether changes were pushed to the repository'
    value: ${{ steps.commit_push.outputs.did_push || 'false' }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0
        fetch-tags: true

    # Detect branch type using the detect-branch-type action
    - name: Detect branch type
      id: branch-type
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/detect-branch-type@main
      with:
        head-branch: ${{ github.head_ref || github.ref_name }}
        major-branch-patterns: ${{ inputs.major-branch-patterns }}
        hotfix-branch-patterns: ${{ inputs.hotfix-branch-patterns }}
        meta-branch-patterns: ${{ inputs.meta-branch-patterns }}

    # Set convenience variables based on branch type
    - name: Set branch flags
      id: meta
      shell: bash
      env:
        BRANCH_TYPE: ${{ steps.branch-type.outputs.branch-type }}
      run: |
        if [[ "$BRANCH_TYPE" == "hotfix" ]]; then
          echo "is_hotfix=true" >> "$GITHUB_OUTPUT"
        else
          echo "is_hotfix=false" >> "$GITHUB_OUTPUT"
        fi
        if [[ "$BRANCH_TYPE" == "meta" ]]; then
          echo "is_meta=true" >> "$GITHUB_OUTPUT"
        else
          echo "is_meta=false" >> "$GITHUB_OUTPUT"
        fi

    # Compute the new version as the first step
    - name: Compute new version
      id: semver
      if: ${{ steps.meta.outputs.is_meta != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/find-next-semver@main
      with:
        major-branch-patterns: ${{ inputs.major-branch-patterns }}
        hotfix-branch-patterns: ${{ inputs.hotfix-branch-patterns }}
        meta-branch-patterns: ${{ inputs.meta-branch-patterns }}

    # Detect last version present in CHANGELOG.rst (first header starting with '## vX.Y.Z - YYYY-MM-DD')
    - name: Determine last CHANGELOG version
      id: changelog_last
      if: ${{ steps.meta.outputs.is_meta != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/get-last-changelog-version@main
      with:
        changelog_path: ${{ inputs.changelog_path }}

    # Compare versions (semantic): result only if new_tag > last_tag
    - name: Check if new version is above last changelog version
      id: should_run
      if: ${{ steps.meta.outputs.is_meta != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/compare-versions@main
      with:
        new_tag: ${{ steps.semver.outputs.new_tag }}
        last_tag: ${{ steps.changelog_last.outputs.last_tag }}

    - name: Find previous release cut
      id: previous_cut
      if: ${{ inputs.workflow_type == 'gitflow' && steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/find-previous-release-cut@main
      with:
        dev_branch: dev
        main_branch: main

    - name: Find current release cut
      id: current_cut
      if: ${{ inputs.workflow_type == 'gitflow' && steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/find-current-release-cut@main
      with:
        dev_branch: dev

    - name: Find PRs on dev between cuts
      id: prs
      if: ${{ inputs.workflow_type == 'gitflow' && steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' && steps.meta.outputs.is_hotfix != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/find-prs-between-cuts@main
      with:
        token: ${{ inputs.gh_token }}
        repo: ${{ github.repository }}
        dev_branch: dev
        prev_cut: ${{ steps.previous_cut.outputs.prev_cut }}
        cur_cut: ${{ steps.current_cut.outputs.cur_cut }}

    # Prepare PR list for changelog depending on branch type
    - name: Prepare PR list for changelog
      id: prs_input
      if: ${{ steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}
      shell: bash
      run: |
        if [[ "${{ inputs.workflow_type }}" != "gitflow" ]] || [[ "${{ steps.meta.outputs.is_hotfix }}" == "true" ]]; then
          echo "numbers=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
        else
          echo "numbers=${{ steps.prs.outputs.numbers }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Build and prepend changelog slice
      if: ${{ steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/update-changelog-slice@main
      with:
        token: ${{ inputs.gh_token }}
        prs: ${{ steps.prs_input.outputs.numbers }}
        version: ${{ steps.semver.outputs.new_tag }}
        changelog_path: ${{ inputs.changelog_path }}

    - name: Commit and push changelog
      id: commit_push
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/commit-push@main
      with:
        pat: ${{ inputs.pat_token }}
        message: "chore: update changelog for ${{ steps.semver.outputs.new_tag }}"
        labels: changelog
      if: ${{ steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}