name: Update Changelog
description: Slice changelog between releases and update CHANGELOG.rst

inputs:
  workflow_type:
    description: 'Type of workflow (gitflow or github-flow)'
    required: false
    default: 'gitflow'
  gh_token:
    description: 'GitHub token for gh CLI'
    required: true
  pat_token:
    description: 'GitHub PAT token for API access'
    required: true
  changelog_path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.rst'
  major-branch-patterns:
    description: 'Comma-separated list of branch patterns for major version bumps (e.g., "major/,breaking/")'
    required: false
    default: 'major/'
  patch-branch-patterns:
    description: 'Comma-separated list of branch patterns for hotfix/patch version bumps (e.g., "hotfix/,patch/")'
    required: false
    default: 'hotfix/'
  meta-branch-patterns:
    description: 'Comma-separated list of branch patterns for non-version-bumping branches (e.g., "meta/,docs/")'
    required: false
    default: 'meta/'

outputs:
  did_push:
    description: 'Whether changes were pushed to the repository'
    value: ${{ steps.commit_push.outputs.did_push || 'false' }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0
        fetch-tags: true

    # Detect branch type using the detect-branch-type action
    - name: Detect branch type
      id: branch-type
      uses: j-moralejo-pinas/ci-cd-python/actions/detect-branch-type@main
      with:
        head-branch: ${{ github.head_ref || github.ref_name }}
        major-branch-patterns: ${{ inputs.major-branch-patterns }}
        patch-branch-patterns: ${{ inputs.patch-branch-patterns }}
        meta-branch-patterns: ${{ inputs.meta-branch-patterns }}

    # Set convenience variables based on branch type
    - name: Set branch flags
      id: meta
      shell: bash
      env:
        BRANCH_TYPE: ${{ steps.branch-type.outputs.branch-type }}
      run: |
        if [[ "$BRANCH_TYPE" == "patch" ]]; then
          echo "is_patch=true" >> "$GITHUB_OUTPUT"
        else
          echo "is_patch=false" >> "$GITHUB_OUTPUT"
        fi
        if [[ "$BRANCH_TYPE" == "meta" ]]; then
          echo "is_meta=true" >> "$GITHUB_OUTPUT"
        else
          echo "is_meta=false" >> "$GITHUB_OUTPUT"
        fi

    # Compute the new version as the first step
    - name: Compute new version
      id: semver
      if: ${{ steps.meta.outputs.is_meta != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python/actions/find-next-semver@main
      with:
        major-branch-patterns: ${{ inputs.major-branch-patterns }}
        patch-branch-patterns: ${{ inputs.patch-branch-patterns }}
        meta-branch-patterns: ${{ inputs.meta-branch-patterns }}

    # Detect last version present in CHANGELOG.rst (first header starting with '## vX.Y.Z - YYYY-MM-DD')
    - name: Determine last CHANGELOG version
      id: changelog_last
      if: ${{ steps.meta.outputs.is_meta != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python/actions/get-last-changelog-version@main
      with:
        changelog_path: ${{ inputs.changelog_path }}

    # Compare versions (semantic): result only if new_tag > last_tag
    - name: Check if new version is above last changelog version
      id: should_run
      if: ${{ steps.meta.outputs.is_meta != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python/actions/compare-versions@main
      with:
        new_tag: ${{ steps.semver.outputs.new_tag }}
        last_tag: ${{ steps.changelog_last.outputs.last_tag }}

    - name: Find PRs on dev between releases
      id: prs_dev
      if: ${{ inputs.workflow_type == 'gitflow' && steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' && steps.meta.outputs.is_patch != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python/actions/find-dev-prs-between-releases@main
      with:
        token: ${{ inputs.gh_token }}
        repo: ${{ github.repository }}
        dev_branch: dev
        main_branch: main

    - name: Find PRs on main between releases
      id: prs_main
      if: ${{ inputs.workflow_type == 'github-flow' && steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' && steps.meta.outputs.is_patch != 'true' }}
      uses: j-moralejo-pinas/ci-cd-python/actions/find-main-prs-between-releases@main
      with:
        token: ${{ inputs.gh_token }}
        repo: ${{ github.repository }}
        main_branch: main
        patch-branch-patterns: ${{ inputs.patch-branch-patterns }}

    # Prepare PR list for changelog depending on branch type and workflow
    - name: Prepare PR list for changelog
      id: prs_input
      if: ${{ steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}
      shell: bash
      run: |
        if [[ "${{ inputs.workflow_type }}" == "gitflow" ]]; then
          if [[ "${{ steps.meta.outputs.is_patch }}" != "true" ]]; then
            echo "numbers=${{ steps.prs_dev.outputs.numbers }}" >> "$GITHUB_OUTPUT"
          else
            echo "numbers=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          fi
        elif [[ "${{ inputs.workflow_type }}" == "github-flow" ]]; then
          if [[ "${{ steps.meta.outputs.is_patch }}" != "true" ]]; then
            echo "numbers=${{ steps.prs_main.outputs.numbers }}" >> "$GITHUB_OUTPUT"
          else
            echo "numbers=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          fi
        else
          # For other workflows (e.g., trunk), don't pass PRs - use commit messages
          echo "numbers=" >> "$GITHUB_OUTPUT"
        fi

    - name: Build and prepend changelog slice
      if: ${{ steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}
      uses: j-moralejo-pinas/ci-cd-python/actions/update-changelog-slice@main
      with:
        token: ${{ inputs.gh_token }}
        prs: ${{ steps.prs_input.outputs.numbers }}
        version: ${{ steps.semver.outputs.new_tag }}
        changelog_path: ${{ inputs.changelog_path }}

    - name: Commit and push changelog
      id: commit_push
      uses: j-moralejo-pinas/ci-cd-python/actions/commit-push@main
      with:
        pat: ${{ inputs.pat_token }}
        message: "chore: update changelog for ${{ steps.semver.outputs.new_tag }}"
        labels: changelog
      if: ${{ steps.meta.outputs.is_meta != 'true' && steps.should_run.outputs.result == 'true' }}