name: Semver Tag
description: Compute next semantic version from PR context, create and push a git tag, and output tag and version.

inputs:
  pat_token:
    description: Personal Access Token with permission to push tags
    required: true
    default: ''
  commit-sha:
    description: 'Specific commit SHA to tag.'
    required: true
  new_tag:
    description: 'Pre-calculated new tag (e.g., vX.Y.Z)'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure git user for tagging
      uses: j-moralejo-pinas/ci-cd-python/actions/git-config@main

    - name: Tag merge commit
      shell: bash
      run: |
        bash "${GITHUB_ACTION_PATH}/tag-merge-commit.sh" \
          "${{ inputs.new_tag }}" \
          "${{ github.event.pull_request.base.ref }}" \
          "${{ inputs.commit-sha }}" \
          "${{ inputs.pat_token }}" \
          "${{ github.repository }}"
