name: 'Check Up To Date'
description: 'Checks if the source branch is up to date with the target branch'
inputs:
  target_branch:
    description: 'The target branch to check against'
    required: true
    default: ${{ github.base_ref }}
  ignore_patterns:
    description: 'Comma-separated list of branch patterns to ignore (e.g. release/*,hotfix/*)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Check up to date
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/check-up-to-date.sh \
          "${{ inputs.target_branch }}" \
          "${{ github.head_ref || github.ref_name }}" \
          "${{ inputs.ignore_patterns }}"
