name: Find Next Semver
description: Determine latest semantic version tag and compute the next one based on PR context.

inputs:
  major-branch-patterns:
    description: 'Comma-separated list of branch patterns for major version bumps (e.g., "major/,breaking/")'
    required: false
    default: 'major/'
  hotfix-branch-patterns:
    description: 'Comma-separated list of branch patterns for hotfix/patch version bumps (e.g., "hotfix/,patch/")'
    required: false
    default: 'hotfix/'
  meta-branch-patterns:
    description: 'Comma-separated list of branch patterns for non-version-bumping branches (e.g., "meta/,docs/")'
    required: false
    default: 'meta/'

outputs:
  latest:
    description: Latest tag found in the repository (vX.Y.Z)
    value: ${{ steps.run.outputs.latest }}
  new_tag:
    description: Next tag to create (vX.Y.Z)
    value: ${{ steps.run.outputs.new_tag }}
  version:
    description: Version without leading v (X.Y.Z)
    value: ${{ steps.run.outputs.version }}

runs:
  using: composite
  steps:
    - name: Detect branch type
      id: branch-type
      uses: j-moralejo-pinas/ci-cd-python/.github/actions/detect-branch-type@main
      with:
        head-branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
        major-branch-patterns: ${{ inputs.major-branch-patterns }}
        hotfix-branch-patterns: ${{ inputs.hotfix-branch-patterns }}
        meta-branch-patterns: ${{ inputs.meta-branch-patterns }}

    - name: Find latest and compute next semver
      id: run
      shell: bash
      env:
        BRANCH_TYPE: ${{ steps.branch-type.outputs.branch-type }}
      run: |
        bash "${GITHUB_ACTION_PATH}/find-next-semver.sh"
