name: Semver Tag
description: Compute next semantic version from PR context, create and push a git tag, and output tag and version.

inputs:
  pat_token:
    description: Personal Access Token with permission to push tags
    required: true
    default: ''
  major-branch-patterns:
    description: 'Comma-separated list of branch patterns for major version bumps (e.g., "major/,breaking/")'
    required: false
    default: 'major/'
  hotfix-branch-patterns:
    description: 'Comma-separated list of branch patterns for hotfix/patch version bumps (e.g., "hotfix/,patch/")'
    required: false
    default: 'fix/,hotfix/,bugfix/'


outputs:
  new_tag:
    description: New tag in the format vX.Y.Z
    value: ${{ steps.find.outputs.new_tag }}
  version:
    description: Version without leading v (X.Y.Z)
    value: ${{ steps.find.outputs.version }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Find latest and next semver
      id: find
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/find-next-semver@main
      with:
        major-branch-patterns: ${{ inputs.major-branch-patterns }}
        hotfix-branch-patterns: ${{ inputs.hotfix-branch-patterns }}

    - name: Configure git user for tagging
      uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/git-config@main

    - name: Tag merge commit
      shell: bash
      env:
        BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha }}
        PAT: ${{ inputs.pat_token }}
      run: |
        bash "${GITHUB_ACTION_PATH}/tag-merge-commit.sh" \
          "${{ steps.find.outputs.new_tag }}" \
          "${BASE_BRANCH}" \
          "${MERGE_SHA}" \
          "${PAT}" \
          "${{ github.repository }}"

    # Version output is provided by the find-next-semver action
