name: Detect Branch Type
description: Determine if a branch is major, minor, or hotfix based on configurable patterns.

inputs:
  head-branch:
    description: 'The branch name to analyze'
    required: true
  major-branch-patterns:
    description: 'Comma-separated list of branch patterns for major version bumps (e.g., "major/,breaking/")'
    required: false
    default: 'major/'
  patch-branch-patterns:
    description: 'Comma-separated list of branch patterns for hotfix/patch version bumps (e.g., "hotfix/,patch/")'
    required: false
    default: 'hotfix/'
  meta-branch-patterns:
    description: 'Comma-separated list of branch patterns for non-version-bumping branches (e.g., "meta/,docs/")'
    required: false
    default: 'meta/'

outputs:
  branch-type:
    description: 'The detected branch type: "major", "patch", "minor", or "meta"'
    value: ${{ steps.detect.outputs.branch_type }}

runs:
  using: composite
  steps:
    - name: Detect branch type
      id: detect
      shell: bash
      env:
        HEAD_BRANCH: ${{ inputs.head-branch }}
        MAJOR_BRANCH_PATTERNS: ${{ inputs.major-branch-patterns }}
        PATCH_BRANCH_PATTERNS: ${{ inputs.patch-branch-patterns }}
        META_BRANCH_PATTERNS: ${{ inputs.meta-branch-patterns }}
      run: |
        bash "${GITHUB_ACTION_PATH}/detect-branch-type.sh"