# GitHub Actions configuration **EXAMPLE**,
# MODIFY IT ACCORDING TO YOUR NEEDS!
# Reference: https://docs.github.com/en/actions

name: dev_pr

on:
  pull_request:
    branches:
      - dev

jobs:
  code-quality:
    name: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: |
          pdm install -G dev

      - name: Fetch and rebase
        run: |
          git fetch origin ${{ github.head_ref }}
          git rebase origin/${{ github.head_ref }}

      - name: Pyupgrade
        run: |
          find src -name "*.py" \
            -exec pdm run pyupgrade --py38-plus --exit-zero-even-if-changed {} +

      - name: Ruff Format Check
        uses: chartboost/ruff-action@v1
        with:
          args: format .

      - name: Docformatter
        run: |
          set +e
          pdm run docformatter --in-place --recursive src/
          code=$?
          if [ "$code" != "0" ] && [ "$code" != "3" ]; then
            exit $code
          fi

      - name: Commit formatting changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "style: autoformat with Ruff" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: test
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies
        run: |
          pdm install -G dev

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/src
          pdm run pytest --cov=src --cov-report=term-missing
